server:
  port: 8090

github:
    client:
        id: Ov23libFQvARjqG8BM54
        secret: 6ccadf84025a5c52820bbea47cb67953d4d9193d
        redirect-uri: http://localhost:8090/callback

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: cgqlbh114514

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1.0.0
