server:
  port: 8090

spring:
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: tnAS6Q3vl4xSb6Tf1aEC

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: cgqlbh114514
    # Druid 连接池配置优化
    druid:
      initial-size: 5              # 初始连接数
      min-idle: 5                  # 最小空闲连接数
      max-active: 20               # 最大活跃连接数
      max-wait: 60000              # 获取连接最大等待时间(60秒)
      time-between-eviction-runs-millis: 60000    # 检测空闲连接的间隔(60秒)
      min-evictable-idle-time-millis: 300000      # 空闲连接最小生存时间(5分钟)
      validation-query: SELECT 1 FROM DUAL        # 验证连接有效性的SQL
      test-while-idle: true        # 空闲时验证连接
      test-on-borrow: false        # 获取连接时不验证(提高性能)
      test-on-return: false        # 归还连接时不验证(提高性能)
      pool-prepared-statements: true              # 开启预编译语句池
      max-pool-prepared-statement-per-connection-size: 20  # 每个连接的预编译语句数量
      filters: stat,wall,slf4j     # 开启监控统计、防火墙、日志功能
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin123

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fake
            client-secret: fake
            redirect-uri: "http://localhost:8090/callback"

  flyway:
    enabled: true
    user: root
    password: cgqlbh114514
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1.0.0

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB

mybatis-plus:
  type-aliases-package: com.lumibee.hive.entity
  global-config:
    db-config:
      id-type: assign_id # 全局主键策略
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 全局逻辑删除值
      logic-not-delete-value: 0 # 全局逻辑未删除值
    banner: false
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换

# 文件存储配置
file:
  upload:
    dir: ./uploads  # 文件上传目录
  base:
    url: /uploads/  # 访问URL前缀

# 头像配置
avatar:
  max:
    size: 2097152   # 头像最大大小 (2MB)
  allowed:
    extensions: jpg,jpeg,png,gif  # 允许的文件类型

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,configprops
  endpoint:
    health:
      show-details: when_authorized
      show-components: always
  metrics:
    export:
      prometheus:
        step: 60s
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jdbc.connections.active: true
  info:
    env:
      enabled: true
    git:
      mode: full

# 日志配置
logging:
  level:
    com.lumibee.hive: INFO
    org.springframework.security: WARN
    com.alibaba.druid: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/hive.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
deepseek:
  api:
    key: sk-2