# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  elasticsearch:
    uris: ${ES_URIS}
    username: ${ES_USERNAME}
    password: ${ES_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GH_CLIENT_ID}
            client-secret: ${GH_CLIENT_SECRET}
            redirect-uri: ${GH_REDIRECT_URI}

elasticsearch:
  index-prefix: prod

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}

logging:
  level:
    com.lumibee.hive: INFO
    org.elasticsearch: WARN
