server:
  port: 8090

spring:
  config:
    import:
        - "optional:application-secret.yml"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: cgqlbh114514

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1.0.0

mybatis-plus:
  type-aliases-package: com.lumibee.hive.entity # 实体类别名包
  global-config:
    db-config:
      id-type: assign_id # 全局主键策略
      logic-delete-field: deleted # 全局逻辑删除字段名 (如果配置了)
      logic-delete-value: 1 # 全局逻辑删除值 (如果配置了)
      logic-not-delete-value: 0 # 全局逻辑未删除值 (如果配置了)
    banner: false # 关闭MP启动时的banner信息
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
    map-underscore-to-camel-case: true # 开启驼峰命名转换

logging.level.org.springframework.security : DEBUG
logging.level.org.springframework.security.web.authentication.rememberme : TRACE
logging.level.com.lumibee.hive.service.UserServiceImpl: DEBUG
