# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: tnAS6Q3vl4xSb6Tf1aEC

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: cgqlbh114514

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fake
            client-secret: fake
            redirect-uri: "http://localhost:8090/callback"

elasticsearch:
  index-prefix: dev

logging:
  level:
    com.lumibee.hive: DEBUG
    org.elasticsearch: DEBUG