# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod

  # --- 数据库配置 ---
  datasource:
    # 直接写入服务名，不再使用 ${DB_URL}
    url: jdbc:mysql://mysql-db:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    # 用户名也直接写入
    username: root
    # 密码可以继续从 .env 读取，因为这部分之前是成功的
    password: ${DB_PASSWORD}

  # --- Redis 配置 ---
  redis:
    # 直接写入服务名，不再使用 ${REDIS_HOST}
    host: redis-cache
    port: 6379
    database: 0
    timeout: 10s
    connect-timeout: 10s
    # password: # 如果Redis有密码则填写
    lettuce:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 200ms
    # 添加连接验证
    client-type: lettuce

  # --- Elasticsearch 配置 ---
  elasticsearch:
    # 直接写入服务名，不再使用 ${ES_URIS}
    uris: http://elasticsearch-search:9200

  # --- Flyway 配置 (可选，但建议保持一致) ---
  flyway:
    url: jdbc:mysql://mysql-db:3306/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    user: root
    password: ${DB_PASSWORD}

  # --- GitHub OAuth 配置 ---
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GH_CLIENT_ID}
            client-secret: ${GH_CLIENT_SECRET}
            redirect-uri: ${GH_REDIRECT_URI}

elasticsearch:
  index-prefix: prod

deepseek:
  api:
    key: ${DEEPSEEK_API_KEY}

file:
  upload:
    dir: /data/uploads  # 匹配Docker映射路径
  base:
    url: /uploads/

logging:
  level:
    com.lumibee.hive: INFO
    org.elasticsearch: WARN
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG
